### ISSUE TITLE
Como cuando la belleza enceguece...

### ISSUE THREAD

**Issue by AlejandroJRosas** [DaikoneKisu/uchamba-frontend#7]
# Colores be like:
## Expectativa
![image](https://github.com/DaikoneKisu/uchamba-frontend/assets/61267550/12115cf0-4b1b-47ad-933d-f6ab05c5e013)
## Realidad
![WhatsApp-Video-2024-01-06-at-1 42 46-AM](https://github.com/DaikoneKisu/uchamba-frontend/assets/61267550/9a32fddc-2096-4ff9-ae63-c30cedf7b7c1)

@Noralgorithm como cuando la belleza enceguece no hay nada que hacer al respecto, que la UCAB cambie los colores

**Comment by DaikoneKisu** [comment]
No veo la foto hijo, pero ya se resolvió
